language: "ko"

reviews:
  profile: "assertive"               # 가장 유사한 공식 옵션 (direct / assertive / chill)
  request_changes_workflow: true     # PR에 변경 요청을 남길지 여부
  collapse_walkthrough: false        # 코드 워크스루 접기 여부

  # 파일 필터링 (include/exclude 대체)
  path_filters:
    - "src/**"
    - "pages/**"
    - "components/**"
    - "lib/**"
    - "hooks/**"

    - "!**/*.md"
    - "!node_modules/**"
    - "!.next/**"
    - "!dist/**"
    - "!coverage/**"

  # 리뷰 댓글 관련 옵션들
  max_comments: 70                   # CodeRabbit 실제 공식 옵션 ✔
  # review_status: "COMMENT"         # COMMENT / APPROVE / REQUEST_CHANGES 중 선택 가능 (최신 버전에서 제거됨)

# CodeRabbit에는 custom rule 시스템이 존재하지 않음 → description들을 가독성용 주석으로 변환
# ----------------------------------------------------------

# Next.js (Pages Router) Best Practices
# - getServerSideProps / getStaticProps 사용 적절성
# - getInitialProps 비추천 여부 확인
# - pages 디렉토리 라우팅 컨벤션 점검
# - next/image 사용 여부

# TypeScript Strictness
# - any 남용 여부
# - 타입 좁히기 가능성
# - optional 체이닝 과사용 여부
# - 타입 추론 가능한 부분

# React Hooks & Component Quality
# - useEffect deps 정확성
# - useCallback/useMemo 최적화 여부
# - 불필요한 re-render 여부
# - props drilling 과도한지 확인

# TailwindCSS Review
# - className 중복 여부
# - 너무 긴 tailwind 조합 개선
# - shadcn/ui와 충돌 여부

# shadcn/ui Best Practices
# - 이미 존재하는 컴포넌트 재사용 권장
# - props 최적화
# - 불필요한 custom component 방지

# Performance & Code Cleanliness
# - 번들 사이즈 개선
# - dynamic import 권장
# - 중복 로직 제거
# - 파일 구조 점검